# Generated by Django 3.0.3 on 2020-02-18 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressType',
            fields=[
                ('addressTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('addressType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BarcodeType',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceType',
            fields=[
                ('complianceTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('complianceType', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('driverId', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='DriverType',
            fields=[
                ('driverTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LicenseClass',
            fields=[
                ('classId', models.IntegerField(primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('locationId', models.IntegerField(primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=10)),
                ('locationCity', models.CharField(max_length=25)),
                ('locationState', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('partId', models.AutoField(primary_key=True, serialize=False)),
                ('partNo', models.CharField(max_length=20)),
                ('partDesc', models.CharField(max_length=100)),
                ('partCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('partQty', models.IntegerField()),
                ('partBarcode', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='PartTransactionTypes',
            fields=[
                ('typeId', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('regionId', models.IntegerField(primary_key=True, serialize=False)),
                ('regionName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplierId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('detailId', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=25)),
                ('isManager', models.BooleanField(default=False)),
                ('isRegionalManager', models.BooleanField(default=False)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Locations')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReconcileLog',
            fields=[
                ('reconcileLogId', models.AutoField(primary_key=True, serialize=False)),
                ('oldCount', models.IntegerField()),
                ('newCount', models.IntegerField()),
                ('diff', models.IntegerField()),
                ('partId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Reconcile',
            fields=[
                ('reconcileId', models.AutoField(primary_key=True, serialize=False)),
                ('reconcileDate', models.DateTimeField()),
                ('reconciledBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartTransactions',
            fields=[
                ('txId', models.IntegerField(primary_key=True, serialize=False)),
                ('txNumber', models.CharField(default=0, max_length=25)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('driverId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Driver')),
                ('typeId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reallytired.PartTransactionTypes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PartTransactionDetail',
            fields=[
                ('detailId', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('partId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reallytired.Part')),
                ('txId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reallytired.PartTransactions')),
            ],
        ),
        migrations.CreateModel(
            name='PartDetail',
            fields=[
                ('partDetailId', models.AutoField(primary_key=True, serialize=False)),
                ('partInv', models.IntegerField()),
                ('partInvCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('locationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Locations')),
                ('partId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='supplierId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Supplier'),
        ),
        migrations.AddField(
            model_name='locations',
            name='regionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Region'),
        ),
        migrations.AddField(
            model_name='driver',
            name='driverTypeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.DriverType'),
        ),
        migrations.AddField(
            model_name='driver',
            name='locationId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.Locations'),
        ),
        migrations.CreateModel(
            name='Compliance',
            fields=[
                ('complianceId', models.IntegerField(primary_key=True, serialize=False)),
                ('licenseNo', models.CharField(max_length=100)),
                ('issueDate', models.DateField()),
                ('expirationDate', models.DateField()),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.LicenseClass')),
                ('complianceTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.ComplianceType')),
                ('driverId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reallytired.Driver')),
            ],
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcodeId', models.IntegerField(primary_key=True, serialize=False)),
                ('barcode', models.CharField(max_length=20)),
                ('partId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reallytired.Part')),
                ('txId', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='reallytired.PartTransactions')),
                ('typeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.BarcodeType')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addressId', models.IntegerField(primary_key=True, serialize=False)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('addressTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reallytired.AddressType')),
            ],
        ),
    ]
